module 1,2. module 3 (1,2)
js-tasks-ru/jsbasic-20201022_bl365 pull request #3
Opened 2020-11-23 15:12 UTC by BL365

2020-11-23 16:42 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-11-23 18:07 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-11-23 21:02 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-11-26 04:49 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-12-06 09:31 UTC, koalex approved these changes

2020-12-06 09:31 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-12-06 09:44 UTC, koalex requested changes
`npm test` не должны выдавать ошибок

2020-12-24 15:03 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-12-24 15:21 UTC, koalex requested changes
Исправь замечания. Запусти локально `npm test`. Если тесты ошибок не выдают, тогда пуляй!

2020-12-24 15:21 UTC, koalex commented on 3-module/5-task/index.js
> +>>>>>>> 5292260a9c3ecfa392534123fb13a4b90bb490ff
что это за строки? `20` и `29`

2020-12-24 15:21 UTC, koalex commented on 2-module/3-task/index.js
> +print(calculator)
откуда туда `print`?

2020-12-24 16:20 UTC, BL365 commented on 3-module/5-task/index.js
> +>>>>>>> 5292260a9c3ecfa392534123fb13a4b90bb490ff
для этой задачи я смотрел решение преподавателя. Когда посмотрел решение написал своё (по сути аналогичное) для закрепления в памяти. Когда пушил возник конфликт. Строки 20 и 29 сгенерированы автоматически для отображения конфликта и запушены ошибочно. Странно что эти строки не вызвали ошибок в npm test и  пуш прошёл.
Сейчас приберу и пропушу по новой

2020-12-24 16:22 UTC, BL365 commented on 2-module/3-task/index.js
> +print(calculator)
остаток отладки, исправляю

2020-12-24 16:47 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Вычислить факториал
+ факториал 0 равен 1
+ факториал 5 равен 120 
+ факториал 3 равен 6 
+ факториал 1 равен 1
```
```diff
Фильтрация по диапазону
+ не должна менять исходный массив
+ должна фильтровать диапазон
```
```diff
Проверка на спам
+ должна возвращать true для '1XbeT now'
+ должна возвращать true для 'free xxxxx'
+ должна возвращать false для 'innocent rabbit'
```
```diff
Усечение строки
+ должна не трогать короткую строку 
+ должна усекать строку 
```
```diff
Трансформировать в массив имён
+ должна преобразовать users в массив имён
```
```diff
Допишите функцию валидации имени пользователя
+ если имя корректное, то true
+ если меньше 4 символов то false
+ если содержит пробелы, то false
```
```diff
Сделать первый символ заглавным
+ должна работать для пустой строки
+ должна работать для строки из одной буквы
+ должна делать первый символ заглавным
```
```diff
Переведите текст вида border-left-width в borderLeftWidth
+ должна преобразовать 'background-color'
+ должна оставить пустую строку без изменений 
+ должна преобразовать 'list-style-image' 
+ должна преобразова��ь '-webkit-transition'
```
```diff
Создайте калькулятор
+ должно складывать числа
+ должно умножать числа
```
```diff
Функция sumSalary(salaries)
+ должна игнорировать свойства других типов
+ должна возвращать 0 если нет свойств с зарплатами
+ должна складывать все зарплаты
```
```diff
Функция makeFriendsList(friends)
+ функция должна возвращать HTML список
+ Число элементов в списке и число объектов в массиве должны быть одинаковыми
+ проверяем содержимое списка
```

Добавляю преподавателя (@koalex) для код-ревью, посмотрим что он скажет :)

2020-12-24 17:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-12-25 04:14 UTC, koalex approved these changes

2020-12-25 04:15 UTC, merged